import React, { useMemo, useState, useCallback } from 'react';
import { Card, Tabs, DataTable, KpiCard, LoadingSkeleton, EmptyState, AlertBanner, Modal, Badge, Button, ConfirmDialog, MiniMap } from 'shared/components';
import type { DataTableColumn } from 'shared/components';
import { useReports, useReportSummary, useReportTypes, useGenerateReport, useDeleteReport } from 'features/reports/hooks/useReports';
import type { ReportRecord, GeneratedReportResponse } from 'features/reports/hooks/useReports';
import toast from 'react-hot-toast';

const REPORT_TYPE_LABEL: Record<string, string> = {
  CRIME_SUMMARY: 'Crime Summary',
  FIR_SUMMARY: 'FIR Summary',
  HOTSPOT_ANALYSIS: 'Hotspot Analysis',
  REPEAT_OFFENDER_ANALYSIS: 'Repeat Offender Analysis',
  NETWORK_ANALYSIS: 'Network Analysis',
  PREDICTIVE_RISK: 'Predictive Risk',
  ANOMALY_DETECTION: 'Anomaly Detection',
  ALERTS_SUMMARY: 'Alerts Summary',
  DISTRICT_REPORT: 'District Report',
  STATION_REPORT: 'Station Report',
};

const STATUS_VARIANT: Record<string, 'success' | 'warning' | 'secondary'> = {
  ACTIVE: 'success',
  INACTIVE: 'secondary',
  ARCHIVED: 'warning',
};

const Reports: React.FC = () => {
  const [selectedReport, setSelectedReport] = useState<ReportRecord | null>(null);
  const [generatedReport, setGeneratedReport] = useState<GeneratedReportResponse | null>(null);
  const [deleteConfirmId, setDeleteConfirmId] = useState<string | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [generateForm, setGenerateForm] = useState({ name: '', report_type: '' });

  const { data: reports, isLoading: reportsLoading, error: reportsError } = useReports({ limit: 100, offset: 0 });
  const { data: summary, isLoading: summaryLoading } = useReportSummary();
  const { data: reportTypes } = useReportTypes();
  const generateMutation = useGenerateReport();
  const deleteMutation = useDeleteReport();

  const reportList = useMemo(() => reports ?? [], [reports]);

  const columns = useMemo<DataTableColumn<ReportRecord>[]>(() => [
    { key: 'name', header: 'Name', render: (r) => r.name },
    {
      key: 'report_type',
      header: 'Type',
      render: (r) => <Badge variant="info">{REPORT_TYPE_LABEL[r.report_type] ?? r.report_type}</Badge>,
    },
    {
      key: 'status',
      header: 'Status',
      render: (r) => <Badge variant={STATUS_VARIANT[r.status] ?? 'secondary'}>{r.status}</Badge>,
    },
    {
      key: 'CREATEDTIME',
      header: 'Generated At',
      render: (r) => (r.CREATEDTIME ? new Date(r.CREATEDTIME).toLocaleString() : '-'),
    },
    {
      key: 'created_by_officer_id',
      header: 'Generated By',
      render: (r) => r.created_by_officer_id || '-',
    },
    {
      key: 'actions',
      header: 'Actions',
      render: (r) => (
        <div className="flex gap-2">
          <Button variant="ghost" size="sm" onClick={() => setSelectedReport(r)}>
            View
          </Button>
          <Button variant="ghost" size="sm" onClick={() => setDeleteConfirmId(r.ROWID)}>
            Delete
          </Button>
        </div>
      ),
    },
  ], []);

  const handleGenerate = useCallback(async () => {
    if (!generateForm.name || !generateForm.report_type) {
      toast.error('Please provide report name and type');
      return;
    }
    setIsGenerating(true);
    try {
      const result = await generateMutation.mutateAsync({
        report_type: generateForm.report_type,
        name: generateForm.name,
        parameters_json: {},
      });
      setGeneratedReport(result);
      toast.success('Report generated successfully');
      setGenerateForm({ name: '', report_type: '' });
    } catch {
      toast.error('Failed to generate report');
    } finally {
      setIsGenerating(false);
    }
  }, [generateForm.name, generateForm.report_type, generateMutation]);

  const handleDelete = useCallback(async () => {
    if (!deleteConfirmId) return;
    try {
      await deleteMutation.mutateAsync(deleteConfirmId);
      toast.success('Report deleted successfully');
      setDeleteConfirmId(null);
      setSelectedReport(null);
    } catch {
      toast.error('Failed to delete report');
    }
  }, [deleteConfirmId, deleteMutation]);

  if (reportsError) {
    return (
      <div className="space-y-6">
        <div>
          <h1 className="text-2xl font-bold text-navy-700 dark:text-white">Reports</h1>
          <p className="text-sm text-gov-slate">Custom and scheduled report generation and export</p>
        </div>
        <AlertBanner variant="error" title="Failed to load reports" message="Unable to fetch reports. Please try again later." />
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-navy-700 dark:text-white">Reports</h1>
        <p className="text-sm text-gov-slate">Custom and scheduled report generation and export</p>
      </div>

      {summaryLoading ? (
        <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-4">
          {Array.from({ length: 4 }).map((_, i) => (
            <Card key={i} className="p-5">
              <LoadingSkeleton variant="card" />
            </Card>
          ))}
        </div>
      ) : summary ? (
        <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-4">
          <KpiCard label="Total Reports" value={summary.total_reports} accent="navy" />
          <KpiCard label="Reports Today" value={summary.reports_today} accent="green" />
          <KpiCard label="Available Types" value={summary.available_report_types} accent="blue" />
          <KpiCard label="Recently Generated" value={reports?.length ?? 0} accent="purple" />
        </div>
      ) : null}

      <Tabs
        items={[
          {
            id: 'custom',
            label: 'Custom Reports',
            content: (
              <div className="space-y-6">
                <Card className="p-6">
                  <h2 className="text-lg font-semibold text-navy-700 dark:text-white">Generate Report</h2>
                  <p className="mt-2 text-sm text-gov-slate">
                    Select a report type and provide a name to generate a new report from existing data.
                  </p>
                  <div className="mt-4 grid grid-cols-1 gap-4 sm:grid-cols-2">
                    <div>
                      <label className="mb-1 block text-sm font-medium text-gray-700">Report Name</label>
                      <input
                        type="text"
                        value={generateForm.name}
                        onChange={(e) => setGenerateForm((f) => ({ ...f, name: e.target.value }))}
                        className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm"
                        placeholder="Enter report name"
                      />
                    </div>
                    <div>
                      <label className="mb-1 block text-sm font-medium text-gray-700">Report Type</label>
                      <select
                        value={generateForm.report_type}
                        onChange={(e) => setGenerateForm((f) => ({ ...f, report_type: e.target.value }))}
                        className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm"
                      >
                        <option value="">Select type</option>
                        {reportTypes?.map((t) => (
                          <option key={t.type} value={t.type}>
                            {t.label}
                          </option>
                        ))}
                      </select>
                    </div>
                  </div>
                  <div className="mt-4">
                    <Button
                      variant="primary"
                      onClick={handleGenerate}
                      disabled={isGenerating || !generateForm.name || !generateForm.report_type}
                    >
                      {isGenerating ? 'Generating...' : 'Generate Report'}
                    </Button>
                  </div>
                </Card>

                <Card className="p-6">
                  <h2 className="mb-4 text-lg font-semibold text-navy-700 dark:text-white">Generated Reports</h2>
                  {reportsLoading ? (
                    <LoadingSkeleton variant="table" rows={5} />
                  ) : reportList.length > 0 ? (
                    <DataTable
                      columns={columns}
                      data={reportList}
                      rowKey={(r) => r.ROWID}
                      emptyTitle="No reports found"
                      emptyDescription="Generate a report to see it here."
                      virtualized={false}
                    />
                  ) : (
                    <EmptyState title="No reports found" description="Generate a report to see it here." />
                  )}
                </Card>
              </div>
            ),
          },
          {
            id: 'scheduled',
            label: 'Scheduled Reports',
            content: (
              <Card className="p-6">
                <h2 className="text-lg font-semibold text-navy-700 dark:text-white">Scheduled Exports</h2>
                <p className="mt-2 text-sm text-gov-slate">
                  Manage recurring daily, weekly, and monthly report schedules for command review.
                </p>
              </Card>
            ),
          },
          {
            id: 'preview',
            label: 'Map Preview',
            content: (
              <Card className="p-4">
                <MiniMap
                  markers={[{ id: 'r1', latitude: 12.9716, longitude: 77.5946, label: 'Report Area' }]}
                  height={240}
                />
              </Card>
            ),
          },
        ]}
      />

      {/* Report Details Modal */}
      <Modal
        isOpen={!!selectedReport}
        onClose={() => setSelectedReport(null)}
        title={selectedReport ? `Report Details — ${selectedReport.name}` : 'Report Details'}
        footer={
          <div className="flex justify-end gap-2">
            <Button variant="ghost" onClick={() => setSelectedReport(null)}>
              Close
            </Button>
            <Button variant="danger" onClick={() => setDeleteConfirmId(selectedReport?.ROWID ?? null)}>
              Delete
            </Button>
          </div>
        }
      >
        {selectedReport && (
          <div className="space-y-4">
            <div className="grid grid-cols-2 gap-4">
              <div>
                <span className="text-sm font-medium text-gray-700">Name</span>
                <p className="text-sm text-gray-900">{selectedReport.name}</p>
              </div>
              <div>
                <span className="text-sm font-medium text-gray-700">Type</span>
                <Badge variant="info">{REPORT_TYPE_LABEL[selectedReport.report_type] ?? selectedReport.report_type}</Badge>
              </div>
              <div>
                <span className="text-sm font-medium text-gray-700">Status</span>
                <Badge variant={STATUS_VARIANT[selectedReport.status] ?? 'secondary'}>{selectedReport.status}</Badge>
              </div>
              <div>
                <span className="text-sm font-medium text-gray-700">Generated By</span>
                <p className="text-sm text-gray-900">{selectedReport.created_by_officer_id || '-'}</p>
              </div>
              <div>
                <span className="text-sm font-medium text-gray-700">Created</span>
                <p className="text-sm text-gray-900">{new Date(selectedReport.CREATEDTIME).toLocaleString()}</p>
              </div>
              <div>
                <span className="text-sm font-medium text-gray-700">Modified</span>
                <p className="text-sm text-gray-900">{new Date(selectedReport.MODIFIEDTIME).toLocaleString()}</p>
              </div>
              {selectedReport.parameters_json && (
                <div className="col-span-2">
                  <span className="text-sm font-medium text-gray-700">Parameters</span>
                  <p className="text-sm text-gray-900">{selectedReport.parameters_json}</p>
                </div>
              )}
            </div>
          </div>
        )}
      </Modal>

      {/* Generated Report Result Modal */}
      <Modal
        isOpen={!!generatedReport}
        onClose={() => setGeneratedReport(null)}
        title={generatedReport ? `Report Generated — ${generatedReport.title}` : 'Report Generated'}
        footer={
          <div className="flex justify-end gap-2">
            <Button variant="ghost" onClick={() => setGeneratedReport(null)}>
              Close
            </Button>
          </div>
        }
      >
        {generatedReport && (
          <div className="space-y-4">
            <div className="grid grid-cols-2 gap-4">
              <div>
                <span className="text-sm font-medium text-gray-700">Report ID</span>
                <p className="text-sm text-gray-900">{generatedReport.report_id}</p>
              </div>
              <div>
                <span className="text-sm font-medium text-gray-700">Type</span>
                <Badge variant="info">{generatedReport.type}</Badge>
              </div>
              <div className="col-span-2">
                <span className="text-sm font-medium text-gray-700">Summary</span>
                <p className="text-sm text-gray-900">{generatedReport.summary}</p>
              </div>
              <div className="col-span-2">
                <span className="text-sm font-medium text-gray-700">Statistics</span>
                <pre className="mt-1 overflow-auto rounded-lg bg-gray-50 p-3 text-xs text-gray-700">
                  {JSON.stringify(generatedReport.statistics, null, 2)}
                </pre>
              </div>
            </div>
          </div>
        )}
      </Modal>

      {/* Delete Confirm Dialog */}
      <ConfirmDialog
        isOpen={!!deleteConfirmId}
        onClose={() => setDeleteConfirmId(null)}
        onConfirm={handleDelete}
        title="Delete Report"
        message="Are you sure you want to delete this report? This action cannot be undone."
        confirmLabel="Delete"
        destructive
      />
    </div>
  );
};

export default Reports;
